import './globals.css';

export const metadata = {
    title: 'chat app',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <main className="flex flex-col items-center">{children}</main>
            </body>
        </html>
    );
}
